{% set name = "zstash" %}
{% set version = "1.4.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/zstash/archive/v{{ version }}.tar.gz
  sha256: 250fd1b566f7334798062caed7f6a60a82b03fbc2f0ca51f8f14c40250351ce5

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - six
    - globus-sdk >=3.0.0,<4.0.0
    - fair-research-login >=0.2.6,<0.3.0

test:
  imports:
    - zstash
  commands:
    - zstash --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/E3SM-Project/zstash
  summary: 'Long term HPSS archiving tool for E3SM'
  license: BSD-3-Clause and custom
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
