{% set name = "zstash" %}
{% set version = "1.4.4rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/zstash/archive/v{{ version }}.tar.gz
  sha256: d0592e9036d1240aa069b9a4ddd4a7c1846b6a2ec3d2935b383e1bedbff239e8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - fair-research-login >=0.2.6,<0.3.0
    - globus-sdk >=3.0.0,<4.0.0
    - six

test:
  imports:
    - zstash
  commands:
    - zstash --help
    # Disabled until we update fair-research-login because of typo:
    # https://github.com/fair-research/native-login/blob/v0.2.6/requirements.txt
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/E3SM-Project/zstash
  summary: 'Long term HPSS archiving tool for E3SM'
  license: BSD-3-Clause and custom
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
