{% set name = "zstash" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/zstash/archive/v{{ version }}.tar.gz
  sha256: fbdc4ffe18041d1488970de45dbe9893f47da1d5d127703fefc38c2af682b536

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - fair-research-login >=0.2.6,<0.3.0
    - globus-sdk >=3.0.0,<4.0.0
    - six

test:
  imports:
    - zstash
  commands:
    - zstash --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/E3SM-Project/zstash
  summary: 'Long term HPSS archiving tool for E3SM'
  license: BSD-3-Clause and custom
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
