schema_version: 1

context:
  name: zstash
  version: "1.6.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/E3SM-Project/zstash/archive/v${{ version }}.tar.gz
  sha256: 0cc846592503f0b82925a2494dedf50b5b838fed2541998b2227a64e26d190ed

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python 3.11.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<3.15
    - sqlite
    - six >=1.16.0
    - globus-sdk >=3.15.0,<4.0.0

tests:
  - python:
      imports:
        - zstash
      pip_check: false
      python_version: 
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - zstash --help

about:
  summary: Long term HPSS archiving tool for E3SM
  license: BSD-3-Clause and LicenseRef-Custom
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/E3SM-Project/zstash

extra:
  recipe-maintainers:
    - andrewdnolan
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
